apiVersion: v1
kind: Namespace
metadata:
  name: miniblog01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blog01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/pv-blog01/
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: miniblog01
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: fbeltrao/miniblog.core:20171130040602
        ports:
          - containerPort: 80
        env:
		  - name: mb-owner
		    value: Francisco Beltrao
		  - name: mb-commentsclosefterdays
		    value: 10
		  - name: mb-postsperpage
		    value: 100
		  - name: mb-username
		    value: kubernetesadmin
		  - name: mb-pwdsalt
		    value: miniblog
		  - name: mb-pwdhash
		    value: 95A805872297C29689F1837697986D52F761FDF771211C3B9E981271A291D16D
		  - name: mb-name
		    value: Kubernetes Blog
		  - name: mb-shortname
		    value: Miniblog in Kubernetes
		  - name: mb-description
		    value: Hosting Miniblog in Kubernetes
		volumeMounts:
		  - name: pv-blog01
            mountPath: /app/data  
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: miniblog01
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web